/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author omkar
 */
import java.awt.Color;
import javax.swing.KeyStroke;
import javax.swing.Timer;
import java.awt.event.*;
import java.util.Random;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
public class FGAME extends javax.swing.JFrame { 
class A{
public void addData(String sql){
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","12345678");
Statement st=con.createStatement();    
int j=st.executeUpdate(sql);
}
catch(Exception e){
       System.out.println(e.getMessage());
}
}
public void showtableData(){    
try{
String sql="select * from highscore order by score desc;";
    DefaultTableModel tm=(DefaultTableModel)jt1.getModel();
    Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","12345678");
Statement st=con.createStatement();    
ResultSet rs=st.executeQuery(sql);
while(rs.next()){
    Object ob[]={rs.getString(1),rs.getInt(2),rs.getDate(3),rs.getTime(4)};
tm.addRow(ob);
}
}
catch(Exception e){
       System.out.println(e.getMessage());
}
}
public String checkData(String sql){
String r = null;
try{
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","12345678");
Statement st=con.createStatement();
ResultSet rs=st.executeQuery(sql);
rs.next();
String p=rs.getString(1);
r=p;
}
catch(Exception e){
       System.out.println(e.getMessage());
}
return r;
}
public boolean checklog(String s){
boolean boo = false;
    try{
String sql="select loginid from userinfo;";
Class.forName("java.sql.Driver");
Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/game","root","12345678");
Statement st=con.createStatement();    
ResultSet rs=st.executeQuery(sql);
while(rs.next()){
String q=rs.getString(1);
if(s.equals(q)){
    boo=true;
    break;
}
else{
    boo=false;
}
}
}
catch(Exception e){
       System.out.println(e.getMessage());
}
    return boo;
}
}
Timer T=new Timer(800, new ActionListener()
{public void actionPerformed(ActionEvent e){
Random a=new Random();
int x=a.nextInt((350-0+1))+0;
Random b=new Random();
int y=b.nextInt((180-0+1))+0;
spot.setLocation(x,y);
}
});
int i=15;
Timer Time=new Timer(1000, new ActionListener()
{public void actionPerformed(ActionEvent e)
{if(i!=-1){NUtime.setText("TIME: "+i);i--;}else{Time.stop();T.stop();
bg1.setText("TIME UP");
spot.setVisible(false);
spot.setEnabled(false);
next.setVisible(true);
next.setEnabled(true);
}
}
});
Timer changecolor=new Timer(800,new ActionListener()
{public void actionPerformed(ActionEvent e)
{Random Rd=new Random();
int r=Rd.nextInt(255);
int g=Rd.nextInt(255);
int b=Rd.nextInt(255);
Color c=new Color(r,g,b);
spot.setBackground(c);
}             
});
int j=4;
Timer bgtimer=new Timer(1000, new ActionListener()
{public void actionPerformed(ActionEvent e)
{
j--;
if(j<=3&&j>0){
bg1.setText(""+j);
}
else if(j==0){
    bg5.setVisible(false);
    bg1.setText("");
    bgtimer.stop();
    T.start();
    Time.start();
    changecolor.start();
    spot.setVisible(true);
    spot.setEnabled(true);
    NUscore.setVisible(true);
    NUtime.setVisible(true);
    score1.setVisible(true);
}
}
});
    /**
     * Creates new form GAME
     */
    public FGAME() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        leaderboardFrame = new javax.swing.JFrame();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        playagain = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        bg3 = new javax.swing.JLabel();
        yourscoreFrame = new javax.swing.JFrame();
        score2 = new javax.swing.JLabel();
        wellplyed = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        showhghscore = new javax.swing.JButton();
        bg2 = new javax.swing.JLabel();
        gameFrame = new javax.swing.JFrame();
        wlcm = new javax.swing.JLabel();
        start = new javax.swing.JButton();
        score1 = new javax.swing.JLabel();
        spot = new javax.swing.JButton();
        next = new javax.swing.JButton();
        NUscore = new javax.swing.JLabel();
        NUtime = new javax.swing.JLabel();
        bg5 = new javax.swing.JLabel();
        bg1 = new javax.swing.JLabel();
        forgotpassFrame2 = new javax.swing.JFrame();
        jLabel22 = new javax.swing.JLabel();
        ans1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        qa = new javax.swing.JTextArea();
        bg9 = new javax.swing.JLabel();
        forgotpassFrame1 = new javax.swing.JFrame();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        login2 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        email1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        bg8 = new javax.swing.JLabel();
        createaccFrame2 = new javax.swing.JFrame();
        jLabel15 = new javax.swing.JLabel();
        ans = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ques = new javax.swing.JTextArea();
        bg7 = new javax.swing.JLabel();
        createaccFrame1 = new javax.swing.JFrame();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        login1 = new javax.swing.JTextField();
        pass1 = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        fullname = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        bg6 = new javax.swing.JLabel();
        loginFrame = new javax.swing.JFrame();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        pass = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        bg4 = new javax.swing.JLabel();
        NUintrotxt = new javax.swing.JLabel();
        NUunderline = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        mainframebg = new javax.swing.JLabel();

        leaderboardFrame.setMinimumSize(new java.awt.Dimension(600, 500));
        leaderboardFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                leaderboardFrameWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                leaderboardFrameWindowActivated(evt);
            }
        });
        leaderboardFrame.getContentPane().setLayout(null);

        jt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jt1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "NAME", "SCORE", "DATE ", "TIME"
            }
        ));
        jScrollPane1.setViewportView(jt1);

        leaderboardFrame.getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 90, 370, 280);

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("LEADERBOARD");
        leaderboardFrame.getContentPane().add(jLabel5);
        jLabel5.setBounds(150, 30, 300, 50);

        playagain.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        playagain.setText("PLAY AGAIN");
        playagain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playagainActionPerformed(evt);
            }
        });
        leaderboardFrame.getContentPane().add(playagain);
        playagain.setBounds(150, 400, 137, 50);

        exit.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        leaderboardFrame.getContentPane().add(exit);
        exit.setBounds(340, 400, 130, 50);

        bg3.setBackground(new java.awt.Color(0, 0, 0));
        bg3.setFont(new java.awt.Font("Times", 0, 90)); // NOI18N
        bg3.setForeground(new java.awt.Color(255, 255, 0));
        bg3.setMinimumSize(new java.awt.Dimension(600, 500));
        bg3.setOpaque(true);
        leaderboardFrame.getContentPane().add(bg3);
        bg3.setBounds(0, 0, 600, 500);

        yourscoreFrame.setMinimumSize(new java.awt.Dimension(600, 500));
        yourscoreFrame.setResizable(false);
        yourscoreFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                yourscoreFrameWindowActivated(evt);
            }
        });
        yourscoreFrame.getContentPane().setLayout(null);

        score2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        score2.setForeground(new java.awt.Color(255, 255, 255));
        yourscoreFrame.getContentPane().add(score2);
        score2.setBounds(260, 180, 110, 40);

        wellplyed.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        wellplyed.setForeground(new java.awt.Color(255, 255, 255));
        wellplyed.setText("WELL PLAYED NAME!");
        yourscoreFrame.getContentPane().add(wellplyed);
        wellplyed.setBounds(150, 70, 340, 50);

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("YOUR SCORE-");
        yourscoreFrame.getContentPane().add(jLabel9);
        jLabel9.setBounds(110, 180, 130, 40);

        showhghscore.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        showhghscore.setText("SHOW HIGH SCORES-->");
        showhghscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showhghscoreActionPerformed(evt);
            }
        });
        yourscoreFrame.getContentPane().add(showhghscore);
        showhghscore.setBounds(180, 310, 280, 70);

        bg2.setBackground(new java.awt.Color(0, 0, 0));
        bg2.setFont(new java.awt.Font("Times", 0, 90)); // NOI18N
        bg2.setForeground(new java.awt.Color(255, 255, 0));
        bg2.setOpaque(true);
        yourscoreFrame.getContentPane().add(bg2);
        bg2.setBounds(0, 0, 600, 500);

        gameFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        gameFrame.setMinimumSize(new java.awt.Dimension(600, 500));
        gameFrame.setResizable(false);
        gameFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                gameFrameWindowClosed(evt);
            }
            public void windowActivated(java.awt.event.WindowEvent evt) {
                gameFrameformWindowActivated(evt);
            }
        });
        gameFrame.getContentPane().setLayout(null);

        wlcm.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        wlcm.setForeground(new java.awt.Color(255, 255, 255));
        wlcm.setText("WELCOME NAME! ");
        gameFrame.getContentPane().add(wlcm);
        wlcm.setBounds(150, 50, 410, 80);

        start.setBackground(new java.awt.Color(0, 0, 0));
        start.setFont(new java.awt.Font("Lucida Grande", 0, 70)); // NOI18N
        start.setForeground(new java.awt.Color(51, 255, 255));
        start.setText("START GAME");
        start.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });
        gameFrame.getContentPane().add(start);
        start.setBounds(60, 160, 480, 280);

        score1.setFont(new java.awt.Font("Seravek", 0, 36)); // NOI18N
        score1.setForeground(new java.awt.Color(255, 255, 255));
        score1.setText("0");
        gameFrame.getContentPane().add(score1);
        score1.setBounds(190, 370, 140, 40);

        spot.setBackground(new java.awt.Color(255, 0, 51));
        spot.setBorderPainted(false);
        spot.setOpaque(true);
        spot.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                spotComponentShown(evt);
            }
        });
        spot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spotActionPerformed(evt);
            }
        });
        gameFrame.getContentPane().add(spot);
        spot.setBounds(100, 240, 40, 40);

        next.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        next.setText("NEXT-->");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        gameFrame.getContentPane().add(next);
        next.setBounds(380, 360, 170, 80);

        NUscore.setFont(new java.awt.Font("Verdana", 0, 36)); // NOI18N
        NUscore.setForeground(new java.awt.Color(255, 255, 255));
        NUscore.setText("SCORE:");
        gameFrame.getContentPane().add(NUscore);
        NUscore.setBounds(30, 360, 150, 60);

        NUtime.setBackground(new java.awt.Color(0, 0, 0));
        NUtime.setFont(new java.awt.Font("Verdana", 0, 28)); // NOI18N
        NUtime.setForeground(new java.awt.Color(255, 255, 255));
        NUtime.setToolTipText("");
        NUtime.setOpaque(true);
        gameFrame.getContentPane().add(NUtime);
        NUtime.setBounds(40, 430, 170, 30);

        bg5.setBackground(new java.awt.Color(0, 0, 0));
        bg5.setFont(new java.awt.Font("Times", 0, 36)); // NOI18N
        bg5.setForeground(new java.awt.Color(255, 255, 0));
        bg5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg5.setText("Game begins in ...");
        bg5.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg5.setMinimumSize(new java.awt.Dimension(600, 500));
        bg5.setOpaque(true);
        bg5.setPreferredSize(new java.awt.Dimension(600, 500));
        gameFrame.getContentPane().add(bg5);
        bg5.setBounds(100, 50, 380, 80);

        bg1.setBackground(new java.awt.Color(0, 0, 0));
        bg1.setFont(new java.awt.Font("Times", 0, 120)); // NOI18N
        bg1.setForeground(new java.awt.Color(255, 255, 0));
        bg1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg1.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg1.setMinimumSize(new java.awt.Dimension(600, 500));
        bg1.setOpaque(true);
        bg1.setPreferredSize(new java.awt.Dimension(600, 500));
        gameFrame.getContentPane().add(bg1);
        bg1.setBounds(0, 0, 600, 500);

        forgotpassFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        forgotpassFrame2.setMinimumSize(new java.awt.Dimension(600, 500));
        forgotpassFrame2.setResizable(false);
        forgotpassFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                forgotpassFrame2formWindowActivated(evt);
            }
        });
        forgotpassFrame2.getContentPane().setLayout(null);

        jLabel22.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("ANSWER");
        forgotpassFrame2.getContentPane().add(jLabel22);
        jLabel22.setBounds(110, 180, 100, 60);

        ans1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ans1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ans1ActionPerformed(evt);
            }
        });
        forgotpassFrame2.getContentPane().add(ans1);
        ans1.setBounds(200, 186, 160, 40);

        jButton6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton6.setText("SHOW PASSWORD");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        forgotpassFrame2.getContentPane().add(jButton6);
        jButton6.setBounds(70, 280, 220, 50);

        jButton10.setText("BACK");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        forgotpassFrame2.getContentPane().add(jButton10);
        jButton10.setBounds(0, 10, 70, 20);

        jButton11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton11.setText("GO TO LOGIN");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        forgotpassFrame2.getContentPane().add(jButton11);
        jButton11.setBounds(320, 280, 170, 50);

        qa.setEditable(false);
        qa.setBackground(new java.awt.Color(0, 0, 0));
        qa.setColumns(20);
        qa.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        qa.setForeground(new java.awt.Color(255, 255, 255));
        qa.setLineWrap(true);
        qa.setRows(5);
        qa.setText("SECURITY QUESTION");
        jScrollPane2.setViewportView(qa);

        forgotpassFrame2.getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 60, 570, 84);

        bg9.setBackground(new java.awt.Color(0, 0, 0));
        bg9.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        bg9.setForeground(new java.awt.Color(255, 255, 255));
        bg9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg9.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg9.setMinimumSize(new java.awt.Dimension(600, 500));
        bg9.setOpaque(true);
        bg9.setPreferredSize(new java.awt.Dimension(600, 500));
        forgotpassFrame2.getContentPane().add(bg9);
        bg9.setBounds(0, 0, 600, 500);

        forgotpassFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        forgotpassFrame1.setMinimumSize(new java.awt.Dimension(600, 500));
        forgotpassFrame1.setResizable(false);
        forgotpassFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                forgotpassFrame1formWindowActivated(evt);
            }
        });
        forgotpassFrame1.getContentPane().setLayout(null);

        jLabel16.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("ENTER LOGIN ID");
        forgotpassFrame1.getContentPane().add(jLabel16);
        jLabel16.setBounds(100, 110, 160, 60);

        jLabel19.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 204, 204));
        jLabel19.setText("FORGOT PASSWORD?");
        forgotpassFrame1.getContentPane().add(jLabel19);
        jLabel19.setBounds(110, 20, 410, 60);

        login2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        login2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login2ActionPerformed(evt);
            }
        });
        forgotpassFrame1.getContentPane().add(login2);
        login2.setBounds(280, 116, 160, 40);

        jButton5.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton5.setText("NEXT->");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        forgotpassFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(210, 300, 190, 50);

        jLabel21.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("ENTER E-MAIL");
        forgotpassFrame1.getContentPane().add(jLabel21);
        jLabel21.setBounds(100, 220, 150, 16);

        email1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        email1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                email1ActionPerformed(evt);
            }
        });
        forgotpassFrame1.getContentPane().add(email1);
        email1.setBounds(280, 200, 260, 40);

        jButton7.setText("BACK");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        forgotpassFrame1.getContentPane().add(jButton7);
        jButton7.setBounds(0, 10, 70, 20);

        bg8.setBackground(new java.awt.Color(0, 0, 0));
        bg8.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        bg8.setForeground(new java.awt.Color(255, 255, 255));
        bg8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg8.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg8.setMinimumSize(new java.awt.Dimension(600, 500));
        bg8.setOpaque(true);
        bg8.setPreferredSize(new java.awt.Dimension(600, 500));
        forgotpassFrame1.getContentPane().add(bg8);
        bg8.setBounds(0, 0, 600, 500);

        createaccFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createaccFrame2.setMinimumSize(new java.awt.Dimension(600, 500));
        createaccFrame2.setResizable(false);
        createaccFrame2.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                createaccFrame2formWindowActivated(evt);
            }
        });
        createaccFrame2.getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("ANSWER");
        createaccFrame2.getContentPane().add(jLabel15);
        jLabel15.setBounds(70, 190, 100, 60);

        ans.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        ans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ansActionPerformed(evt);
            }
        });
        createaccFrame2.getContentPane().add(ans);
        ans.setBounds(180, 200, 160, 40);

        jButton4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton4.setText("CREATE ACCOUNT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        createaccFrame2.getContentPane().add(jButton4);
        jButton4.setBounds(90, 280, 220, 50);

        jLabel18.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("ENTER SECURITY QUESTION");
        createaccFrame2.getContentPane().add(jLabel18);
        jLabel18.setBounds(10, 90, 330, 24);

        jButton9.setText("BACK");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        createaccFrame2.getContentPane().add(jButton9);
        jButton9.setBounds(0, 10, 70, 20);

        jButton12.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton12.setText("LOGIN");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        createaccFrame2.getContentPane().add(jButton12);
        jButton12.setBounds(350, 280, 105, 50);

        ques.setColumns(20);
        ques.setFont(new java.awt.Font("Lucida Grande", 0, 20)); // NOI18N
        ques.setLineWrap(true);
        ques.setRows(5);
        ques.setWrapStyleWord(true);
        jScrollPane3.setViewportView(ques);

        createaccFrame2.getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(250, 80, 330, 100);

        bg7.setBackground(new java.awt.Color(0, 0, 0));
        bg7.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        bg7.setForeground(new java.awt.Color(255, 255, 255));
        bg7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg7.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg7.setMinimumSize(new java.awt.Dimension(600, 500));
        bg7.setOpaque(true);
        bg7.setPreferredSize(new java.awt.Dimension(600, 500));
        createaccFrame2.getContentPane().add(bg7);
        bg7.setBounds(0, 0, 600, 500);

        createaccFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        createaccFrame1.setMinimumSize(new java.awt.Dimension(600, 500));
        createaccFrame1.setResizable(false);
        createaccFrame1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                createaccFrame1formWindowActivated(evt);
            }
        });
        createaccFrame1.getContentPane().setLayout(null);

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("LOGIN ID");
        createaccFrame1.getContentPane().add(jLabel10);
        jLabel10.setBounds(100, 170, 100, 60);

        jLabel11.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("PASSWORD");
        createaccFrame1.getContentPane().add(jLabel11);
        jLabel11.setBounds(100, 240, 150, 60);

        jLabel12.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 204, 204));
        jLabel12.setText("CREATE ACCOUNT");
        createaccFrame1.getContentPane().add(jLabel12);
        jLabel12.setBounds(160, 20, 340, 60);

        login1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        login1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login1ActionPerformed(evt);
            }
        });
        createaccFrame1.getContentPane().add(login1);
        login1.setBounds(280, 180, 160, 40);

        pass1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createaccFrame1.getContentPane().add(pass1);
        pass1.setBounds(280, 250, 160, 40);

        jButton3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton3.setText("NEXT->");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        createaccFrame1.getContentPane().add(jButton3);
        jButton3.setBounds(200, 370, 190, 50);

        fullname.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        fullname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fullnameActionPerformed(evt);
            }
        });
        createaccFrame1.getContentPane().add(fullname);
        fullname.setBounds(280, 110, 160, 40);

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("ENTER FULL NAME");
        createaccFrame1.getContentPane().add(jLabel13);
        jLabel13.setBounds(100, 120, 170, 24);

        jLabel14.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ENTER E-MAIL");
        createaccFrame1.getContentPane().add(jLabel14);
        jLabel14.setBounds(100, 320, 150, 16);

        email.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createaccFrame1.getContentPane().add(email);
        email.setBounds(280, 310, 260, 40);

        jButton8.setText("BACK");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        createaccFrame1.getContentPane().add(jButton8);
        jButton8.setBounds(0, 10, 70, 20);

        bg6.setBackground(new java.awt.Color(0, 0, 0));
        bg6.setFont(new java.awt.Font("Times", 0, 18)); // NOI18N
        bg6.setForeground(new java.awt.Color(255, 255, 255));
        bg6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg6.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg6.setMinimumSize(new java.awt.Dimension(600, 500));
        bg6.setOpaque(true);
        bg6.setPreferredSize(new java.awt.Dimension(600, 500));
        createaccFrame1.getContentPane().add(bg6);
        bg6.setBounds(0, 0, 600, 500);

        loginFrame.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        loginFrame.setMinimumSize(new java.awt.Dimension(600, 500));
        loginFrame.setResizable(false);
        loginFrame.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                loginFrameformWindowActivated(evt);
            }
        });
        loginFrame.getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LOGIN ID");
        loginFrame.getContentPane().add(jLabel1);
        jLabel1.setBounds(150, 110, 100, 60);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PASSWORD");
        loginFrame.getContentPane().add(jLabel2);
        jLabel2.setBounds(150, 170, 120, 60);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("LOGIN ");
        loginFrame.getContentPane().add(jLabel3);
        jLabel3.setBounds(240, 20, 200, 60);

        login.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(login);
        login.setBounds(280, 120, 160, 40);

        pass.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        loginFrame.getContentPane().add(pass);
        pass.setBounds(280, 180, 160, 40);

        jButton2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton2.setText("ENTER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        loginFrame.getContentPane().add(jButton2);
        jButton2.setBounds(199, 259, 190, 50);

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 102, 255));
        jLabel4.setText("<html><body><u>Forgot Password?</u></body></html> ");
        jLabel4.setToolTipText("");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        loginFrame.getContentPane().add(jLabel4);
        jLabel4.setBounds(170, 330, 110, 22);

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 102, 255));
        jLabel6.setText("<html><body><u>Create new account</u></body></html> ");
        jLabel6.setToolTipText("");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        loginFrame.getContentPane().add(jLabel6);
        jLabel6.setBounds(310, 330, 150, 22);

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 102, 255));
        jLabel7.setText("|");
        jLabel7.setToolTipText("");
        loginFrame.getContentPane().add(jLabel7);
        jLabel7.setBounds(290, 330, 20, 22);

        bg4.setBackground(new java.awt.Color(0, 0, 0));
        bg4.setFont(new java.awt.Font("Times", 0, 120)); // NOI18N
        bg4.setForeground(new java.awt.Color(255, 255, 0));
        bg4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bg4.setMaximumSize(new java.awt.Dimension(1000, 1000));
        bg4.setMinimumSize(new java.awt.Dimension(600, 500));
        bg4.setOpaque(true);
        bg4.setPreferredSize(new java.awt.Dimension(600, 500));
        loginFrame.getContentPane().add(bg4);
        bg4.setBounds(0, 0, 600, 500);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        setMinimumSize(new java.awt.Dimension(600, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(null);

        NUintrotxt.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        NUintrotxt.setForeground(new java.awt.Color(255, 255, 0));
        NUintrotxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUintrotxt.setText("Whac-A-Mole");
        getContentPane().add(NUintrotxt);
        NUintrotxt.setBounds(30, 50, 530, 180);

        NUunderline.setFont(new java.awt.Font("Tahoma", 1, 60)); // NOI18N
        NUunderline.setForeground(new java.awt.Color(0, 255, 255));
        NUunderline.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NUunderline.setText("____________");
        getContentPane().add(NUunderline);
        NUunderline.setBounds(30, 60, 530, 180);

        jButton1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jButton1.setText("PLAY");
        jButton1.addMouseWheelListener(new java.awt.event.MouseWheelListener() {
            public void mouseWheelMoved(java.awt.event.MouseWheelEvent evt) {
                jButton1MouseWheelMoved(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(200, 270, 190, 110);

        mainframebg.setBackground(new java.awt.Color(0, 0, 0));
        mainframebg.setOpaque(true);
        getContentPane().add(mainframebg);
        mainframebg.setBounds(-65, -24, 1020, 770);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void showhghscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showhghscoreActionPerformed
leaderboardFrame.setVisible(true);
score2.setText(score1.getText());
String lid=login.getText();
String sql1="select name from userinfo where loginid='"+lid+"';";
A ob=new A();
String NAME=ob.checkData(sql1);
int s=Integer.parseInt(score1.getText());
String sql2="insert into highscore values('"+NAME+"',"+s+",date(sysdate()),time(sysdate()));";
ob.addData(sql2);

// TODO add your handling code here:
    }//GEN-LAST:event_showhghscoreActionPerformed

    private void playagainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playagainActionPerformed
i=15;
j=4;
gameFrame.setVisible(true);
gameFrame.setLocationRelativeTo(leaderboardFrame);
bg1.setText("");
wlcm.setVisible(true);
start.setVisible(true);
start.setEnabled(true);
spot.setVisible(false);
spot.setEnabled(false);
next.setEnabled(false);
next.setVisible(false);
NUscore.setVisible(false);
NUtime.setVisible(false);
score1.setText(""+0);
score1.setVisible(false);
spot.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
DefaultTableModel tm=(DefaultTableModel)jt1.getModel();
tm.setRowCount(0);
    }//GEN-LAST:event_playagainActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
System.exit(0);        
    }//GEN-LAST:event_exitActionPerformed

    private void leaderboardFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_leaderboardFrameWindowActivated
leaderboardFrame.setLocationRelativeTo(yourscoreFrame);
A ob=new A();
ob.showtableData();
    }//GEN-LAST:event_leaderboardFrameWindowActivated

    private void spotComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_spotComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_spotComponentShown

    private void spotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spotActionPerformed
 int z=Integer.parseInt(score1.getText());
        score1.setText(""+(z+1));
    }//GEN-LAST:event_spotActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
yourscoreFrame.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    private void gameFrameformWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_gameFrameformWindowActivated
gameFrame.setLocationRelativeTo(loginFrame);
String lid=login.getText();
String sql="select name from userinfo where loginid='"+lid+"';";
A ob=new A();
String NAME=ob.checkData(sql);
wlcm.setText("WELCOME "+NAME+"!");
bg5.setVisible(false);
spot.setVisible(false);
spot.setEnabled(false);
next.setEnabled(false);
next.setVisible(false);
NUscore.setVisible(false);
NUtime.setVisible(false);
score1.setVisible(false);
spot.getInputMap().put(KeyStroke.getKeyStroke("SPACE"), "none");
spot.getInputMap().put(KeyStroke.getKeyStroke("ENTER"), "none"); 
// TODO add your handling code here:
    }//GEN-LAST:event_gameFrameformWindowActivated

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
loginFrame.setVisible(true);       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
wlcm.setVisible(false);
start.setVisible(false);
start.setEnabled(false);
bg5.setVisible(true);
bgtimer.start();

// TODO add your handling code here:
    }//GEN-LAST:event_startActionPerformed

    private void jButton1MouseWheelMoved(java.awt.event.MouseWheelEvent evt) {//GEN-FIRST:event_jButton1MouseWheelMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseWheelMoved

    private void yourscoreFrameWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_yourscoreFrameWindowActivated
yourscoreFrame.setLocationRelativeTo(gameFrame);  
String lid=login.getText();
String sql="select name from userinfo where loginid='"+lid+"';";
A ob=new A();
String NAME=ob.checkData(sql);
wellplyed.setText("WELL PLAYED "+NAME+"!");
score2.setText(score1.getText());
// TODO add your handling code here:
    }//GEN-LAST:event_yourscoreFrameWindowActivated

    private void loginFrameformWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_loginFrameformWindowActivated
loginFrame.setLocationRelativeTo(this);
//clearing create frame 
fullname.setText(null);
login1.setText(null);
pass1.setText(null);
email.setText(null);
ques.setText("Eg: Who was your favourite school  teacher?");
ans.setText(null);
//clearing forgot pass frame
login2.setText(null);
email1.setText(null);
qa.setText(null);
ans1.setText(null);
    }//GEN-LAST:event_loginFrameformWindowActivated

    private void loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_loginActionPerformed

    private void login1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login1ActionPerformed

    private void createaccFrame1formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createaccFrame1formWindowActivated
createaccFrame1.setLocationRelativeTo(loginFrame);          // TODO add your handling code here:
    }//GEN-LAST:event_createaccFrame1formWindowActivated

    private void fullnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fullnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fullnameActionPerformed

    private void ansActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ansActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ansActionPerformed

    private void createaccFrame2formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_createaccFrame2formWindowActivated
createaccFrame2.setLocationRelativeTo(createaccFrame1);
ques.setText("Eg: What was your favourite subject in school?");
    }//GEN-LAST:event_createaccFrame2formWindowActivated

    private void login2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login2ActionPerformed

    private void forgotpassFrame1formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_forgotpassFrame1formWindowActivated
forgotpassFrame1.setLocationRelativeTo(loginFrame);         
    }//GEN-LAST:event_forgotpassFrame1formWindowActivated

    private void ans1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ans1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ans1ActionPerformed

    private void forgotpassFrame2formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_forgotpassFrame2formWindowActivated
forgotpassFrame2.setLocationRelativeTo(forgotpassFrame1);       
A ob=new A();
String sql1="select ques from userinfo where loginid='"+login2.getText()+"';";
String quest=ob.checkData(sql1);
qa.setText("SECURITY QUESTION-"+quest);





// TODO add your handling code here:
    }//GEN-LAST:event_forgotpassFrame2formWindowActivated

    private void email1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_email1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_email1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
char[] ch=pass.getPassword();
String pwd=new String(ch);   
String lid=login.getText();
String sql1="select pass from userinfo where loginid='"+lid+"';";
String sql2="select name from userinfo where loginid='"+lid+"';";
A ob=new A();
String p=ob.checkData(sql1);//original pass
String NAME=ob.checkData(sql2);//****IMP original name
boolean boo=ob.checklog(lid);
if(boo){
           if(pwd.equals(p)){
    gameFrame.setVisible(true);
           }
         else{
    JOptionPane.showMessageDialog(null,"WRONG PASSWORD");
             }
}
else{
    JOptionPane.showMessageDialog(null,"ENTER CORRECT LOGINID");  
}
      
    }//GEN-LAST:event_jButton2ActionPerformed

    private void leaderboardFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_leaderboardFrameWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_leaderboardFrameWindowClosed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
forgotpassFrame1.setVisible(true);      
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
createaccFrame1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
String lid=login2.getText();
String em=email1.getText();
String sql="select email from userinfo where loginid='"+lid+"';";
A ob=new A();
String ema=ob.checkData(sql);
boolean boo=ob.checklog(lid);
if(boo){
           if(em.equals(ema)){
    forgotpassFrame2.setVisible(true);
           }
         else{
    JOptionPane.showMessageDialog(null,"ENTER CORRECT EMAIL ID");
             }
}
else{
    JOptionPane.showMessageDialog(null,"ENTER CORRECT LOGINID");  
}

// TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
loginFrame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
loginFrame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
createaccFrame1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
forgotpassFrame1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
createaccFrame2.setVisible(true);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
String a=ans1.getText();
String sql2="select ans from userinfo where loginid='"+login2.getText()+"';";
String sql3="select pass from userinfo where loginid='"+login2.getText()+"';";
A ob=new A();
String answ=ob.checkData(sql2);
String pa=ob.checkData(sql3);
if(a.equals(answ)){
JOptionPane.showMessageDialog(null,"YOUR PASSWORD IS "+pa);
}
else{
    JOptionPane.showMessageDialog(null,"WRONG ANSWER");
}// TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
loginFrame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
String f=fullname.getText();
String l=login1.getText();
char ch[]=pass1.getPassword();
String p=new String(ch);
String e=email.getText();
String q=ques.getText();
String a=ans.getText();
String sql="insert into userinfo values('"+f+"','"+l+"','"+p+"','"+e+"','"+q+"','"+a+"');";
A ob=new A();
ob.addData(sql);
JOptionPane.showMessageDialog(null,"ACCOUNT CREATED");




// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
loginFrame.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void gameFrameWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_gameFrameWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_gameFrameWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FGAME.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FGAME().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel NUintrotxt;
    private javax.swing.JLabel NUscore;
    private javax.swing.JLabel NUtime;
    private javax.swing.JLabel NUunderline;
    private javax.swing.JTextField ans;
    private javax.swing.JTextField ans1;
    private javax.swing.JLabel bg1;
    private javax.swing.JLabel bg2;
    private javax.swing.JLabel bg3;
    private javax.swing.JLabel bg4;
    private javax.swing.JLabel bg5;
    private javax.swing.JLabel bg6;
    private javax.swing.JLabel bg7;
    private javax.swing.JLabel bg8;
    private javax.swing.JLabel bg9;
    private javax.swing.JFrame createaccFrame1;
    private javax.swing.JFrame createaccFrame2;
    private javax.swing.JTextField email;
    private javax.swing.JTextField email1;
    private javax.swing.JButton exit;
    private javax.swing.JFrame forgotpassFrame1;
    private javax.swing.JFrame forgotpassFrame2;
    private javax.swing.JTextField fullname;
    private javax.swing.JFrame gameFrame;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jt1;
    private javax.swing.JFrame leaderboardFrame;
    private javax.swing.JTextField login;
    private javax.swing.JTextField login1;
    private javax.swing.JTextField login2;
    private javax.swing.JFrame loginFrame;
    private javax.swing.JLabel mainframebg;
    private javax.swing.JButton next;
    private javax.swing.JPasswordField pass;
    private javax.swing.JPasswordField pass1;
    private javax.swing.JButton playagain;
    private javax.swing.JTextArea qa;
    private javax.swing.JTextArea ques;
    private javax.swing.JLabel score1;
    private javax.swing.JLabel score2;
    private javax.swing.JButton showhghscore;
    private javax.swing.JButton spot;
    private javax.swing.JButton start;
    private javax.swing.JLabel wellplyed;
    private javax.swing.JLabel wlcm;
    private javax.swing.JFrame yourscoreFrame;
    // End of variables declaration//GEN-END:variables
}
